name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Restore cached
      uses: actions/cache/restore@v4
      with:
        key: cache
        path: cache
    - name: Install Dependencies
      run: ./install.sh
    - name: Build artifacts
      run: ./build.sh
    - uses: coder/wush-action@v1.0.0
      timeout-minutes: 15
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: output
        compression-level: 0
    - name: Save cached
      uses: actions/cache/save@v4
      with:
        key: cache
        path: cache
