name: CI
on: [push]
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: false
    - name: Restore cached
      uses: actions/cache/restore@v4
      with:
        key: cache
        path: cache
    - name: Install Dependencies
      run: ./install.sh
    - name: Build artifacts
      run: ./build.sh
    - name: Check Runner Environment
      run: |
        tty
        which bash
        which tmux
        which clear
        which tput
        if [ -f /usr/share/terminfo/x/xterm-256color ]; then
          echo "terminfo for xterm-256color found."
        else
          echo "Warning: terminfo for xterm-256color NOT found."
        fi
    - name: Setup upterm session
      uses: ento/action-upterm@arm64
      with:
        limit-access-to-actor: true
        limit-access-to-users: My9xVm
        wait-timeout-minutes: 15
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4
      with:
        path: output
        compression-level: 0
    - name: Save cached
      uses: actions/cache/save@v4
      with:
        key: cache
        path: cache
